language: node_js
node_js:
- 8.4.0
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
  - openssl aes-256-cbc -K $encrypted_c3f8877c0d24_key -iv $encrypted_c3f8877c0d24_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
